export const IMAGESCIVILLIGHT = {
  clear: require("../../assets/weatherIcons/weathercivillight/clear.png"),
  cloudy: require("../../assets/weatherIcons/weathercivillight/cloudy.png"),
  humid: require("../../assets/weatherIcons/weathercivillight/humid.png"),
  ishower: require("../../assets/weatherIcons/weathercivillight/ishower.png"),
  lightrain: require("../../assets/weatherIcons/weathercivillight/lightrain.png"),
  lightsnow: require("../../assets/weatherIcons/weathercivillight/lightsnow.png"),
  mcloudy: require("../../assets/weatherIcons/weathercivillight/mcloudy.png"),
  oshower: require("../../assets/weatherIcons/weathercivillight/oshower.png"),
  pcloudy: require("../../assets/weatherIcons/weathercivillight/pcloudy.png"),
  rain: require("../../assets/weatherIcons/weathercivillight/rain.png"),
  rainsnow: require("../../assets/weatherIcons/weathercivillight/rainsnow.png"),
  snow: require("../../assets/weatherIcons/weathercivillight/snow.png"),
  ts: require("../../assets/weatherIcons/weathercivillight/ts.png"),
  tsrain: require("../../assets/weatherIcons/weathercivillight/tsrain.png"),
};

export const WIND = {
  E: require("../../assets/weatherIcons/wind/leste.gif"),
  NE: require("../../assets/weatherIcons/wind/nordeste.gif"),
  NW: require("../../assets/weatherIcons/wind/noroeste.gif"),
  N: require("../../assets/weatherIcons/wind/norte.gif"),
  W: require("../../assets/weatherIcons/wind/oeste.gif"),
  SE: require("../../assets/weatherIcons/wind/sudeste.gif"),
  SW: require("../../assets/weatherIcons/wind/sudoeste.gif"),
  S: require("../../assets/weatherIcons/wind/sul.gif"),
};

// CPTEC API GOV
// export const WIND = {
//   estenordeste: require("../../assets/weatherIcons/wind/este-nordeste.gif"),
//   estesudeste: require("../../assets/weatherIcons/wind/este-sudeste.gif"),
//   leste: require("../../assets/weatherIcons/wind/leste.gif"),
//   ND: require("../../assets/weatherIcons/wind/ND.gif"),
//   nordeste: require("../../assets/weatherIcons/wind/nordeste.gif"),
//   nornordeste: require("../../assets/weatherIcons/wind/nor-nordeste.gif"),
//   nornoroeste: require("../../assets/weatherIcons/wind/nor-noroeste.gif"),
//   noroeste: require("../../assets/weatherIcons/wind/noroeste.gif"),
//   norte: require("../../assets/weatherIcons/wind/norte.gif"),
//   oeste: require("../../assets/weatherIcons/wind/oeste.gif"),
//   oestenoroeste: require("../../assets/weatherIcons/wind/oeste-noroeste.gif"),
//   oestesudoeste: require("../../assets/weatherIcons/wind/oeste-sudoeste.gif"),
//   sudeste: require("../../assets/weatherIcons/wind/sudeste.gif"),
//   sudoeste: require("../../assets/weatherIcons/wind/sudoeste.gif"),
//   sul: require("../../assets/weatherIcons/wind/sul.gif"),
//   sulsudeste: require("../../assets/weatherIcons/wind/sul-sudeste.gif"),
//   sulsudoeste: require("../../assets/weatherIcons/wind/sul-sudoeste.gif"),
// };

// WEATHER CIVIL

export const IMAGESCIVIL = {
  clearday: require("../../assets/weatherIcons/weathercivil/clearday.png"),
  clearnight: require("../../assets/weatherIcons/weathercivil/clearnight.png"),
  cloudyday: require("../../assets/weatherIcons/weathercivil/cloudyday.png"),
  cloudynight: require("../../assets/weatherIcons/weathercivil/cloudynight.png"),
  humidday: require("../../assets/weatherIcons/weathercivil/humidday.png"),
  humidnight: require("../../assets/weatherIcons/weathercivil/humidnight.png"),
  ishowerday: require("../../assets/weatherIcons/weathercivil/ishowerday.png"),
  ishowernight: require("../../assets/weatherIcons/weathercivil/ishowernight.png"),
  lightrainday: require("../../assets/weatherIcons/weathercivil/lightrainday.png"),
  lightrainnight: require("../../assets/weatherIcons/weathercivil/lightrainnight.png"),
  lightsnowday: require("../../assets/weatherIcons/weathercivil/lightsnowday.png"),
  lightsnownight: require("../../assets/weatherIcons/weathercivil/lightsnownight.png"),
  mcloudyday: require("../../assets/weatherIcons/weathercivil/mcloudyday.png"),
  mcloudynight: require("../../assets/weatherIcons/weathercivil/mcloudynight.png"),
  oshowerday: require("../../assets/weatherIcons/weathercivil/oshowerday.png"),
  oshowernight: require("../../assets/weatherIcons/weathercivil/oshowernight.png"),
  pcloudyday: require("../../assets/weatherIcons/weathercivil/pcloudyday.png"),
  pcloudynight: require("../../assets/weatherIcons/weathercivil/pcloudynight.png"),
  rainday: require("../../assets/weatherIcons/weathercivil/rainday.png"),
  rainnight: require("../../assets/weatherIcons/weathercivil/rainnight.png"),
  rainsnowday: require("../../assets/weatherIcons/weathercivil/rainsnowday.png"),
  rainsnownight: require("../../assets/weatherIcons/weathercivil/rainsnownight.png"),
  snowday: require("../../assets/weatherIcons/weathercivil/snowday.png"),
  snownight: require("../../assets/weatherIcons/weathercivil/snownight.png"),
  tsday: require("../../assets/weatherIcons/weathercivil/tsday.png"),
  tsnight: require("../../assets/weatherIcons/weathercivil/tsnight.png"),
  tsrainday: require("../../assets/weatherIcons/weathercivil/tsrainday.png"),
  tsrainnight: require("../../assets/weatherIcons/weathercivil/tsrainnight.png"),
};
